server:
  port: 8080
  context-path: /app-hive-mserver
  tomcat-uri-encoding: UTF-8
#redis集群
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 20000
#    集群环境打开下面注释，单机不需要打开
#    cluster:
#      集群信息
#      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
#      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
#      maxRedirects: 3
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password:
  application:
    name: spring-boot-redis

  datasource:
      url: jdbc:mysql://localhost:3306/app-hive?useUnicode=true&characterEncoding=UTF-8&useSSL=false #配置数据库的路径
      username: root #数据库登录名
      password: 123456 #登陆密码
      type: com.alibaba.druid.pool.DruidDataSource  #这个可以看一下 https://blog.csdn.net/qq_27191423/article/details/79146855
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20 #连接池的最大值，同一时间可以从池分配的最多连接数量，0时无限制
      initialSize: 1 #连接初始值，连接池启动时创建的连接数量的初始值
      maxWait: 60000
      minIdle: 1 #最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true #是否对已备语句进行池管理（布尔值），是否对PreparedStatement进行缓存
      maxOpenPreparedStatements: 20